### ISSUE TITLE
Can linter-flow-plus be used concurrently with nuclide?

### ISSUE THREAD

**Issue by tonyxiao** [nmn/linter-flow-plus#11]
Ideally I'd still like to keep nuclide's other features but switch the flow type checking to linter-flow-plus only.

**Comment by nmn** [comment]
I currently do that myself. Nuclide's config is weird, so I'm not sure how to reproduce the setup exactly. But I use `linter-flow` and `autocomplete-flow` packages, and rely on Nuclide for type tooltips and click-to-definition.

That said, use `linter-flow` not this package. I'm a contributor on that package. It started as a clone of this package, but has received updates every since. If you have any problems with `linter-flow` please create an issue there, and we'll take care of it.

**Comment by tonyxiao** [comment]
👍 I got it to work too. Thanks
